#!/usr/bin/env python3
# tutorial.py — tutorial-cli-todo: a minimal command-line todo list.
#
# Generated by the SPARC+Design refinement stage (MiniMax M3, sparc-refinement profile).
# This file is the production-ready Python implementation that
# follows from the upstream spec / design / pseudocode / architecture
# artifacts in this directory.
#
# Usage:
#   ./tutorial.py add "buy milk"          # add a todo, prints "added todo N: <text>"
#   ./tutorial.py list [--done | --open]  # list todos (default: all)
#   ./tutorial.py done <id>               # mark a todo as done (idempotent)
#   ./tutorial.py delete <id>             # remove a todo by id
#   ./tutorial.py help                    # print usage
#
# Storage: $HOME/.tutorial_todo.json (override with --store PATH).
# Atomic write: temp file + os.replace(). Mode 0600 on first creation;
# preserve existing mode on subsequent writes (per spec US-1).
# Exit codes: 0 success, 2 user error, 3 I/O / corruption.
# Python 3.8+ stdlib only. No third-party deps.

import argparse
import json
import os
import sys
import tempfile
from datetime import datetime, timezone

VERSION = 1
DEFAULT_PATH = os.path.join(os.path.expanduser("~"), ".tutorial_todo.json")
EXIT_OK = 0
EXIT_USAGE = 2
EXIT_IO = 3


class NoSuchId(Exception):
    """Raised by find_todo when an id is missing or invalid."""
    def __init__(self, tid):
        self.tid = tid
        super().__init__(f"no todo with id {tid}")


def err(msg, code):
    """Print msg to stderr and exit with code."""
    print(msg, file=sys.stderr)
    sys.exit(code)


def now_iso():
    """Single canonical timestamp helper. UTC, ISO-8601, seconds precision."""
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def make_id(todos):
    """Monotonic integer id, starting at 1. Stable across deletes."""
    if not todos:
        return 1
    return max(t["id"] for t in todos) + 1


def find_todo(todos, tid):
    """Return the todo with id=tid, or raise NoSuchId.

    Rejects id 0 and negative ids as 'not found' (caller prints the
    same error either way — spec doesn't require distinguishing).
    """
    if tid is None or tid < 1:
        raise NoSuchId(tid)
    for t in todos:
        if t["id"] == tid:
            return t
    raise NoSuchId(tid)


def load_store(path):
    """Read the JSON store at `path`. Returns the todos list.

    - Missing file -> [] (first-run state, not an error).
    - Malformed JSON -> exit 3 (refuse to start, do NOT overwrite).
    - Permission error -> exit 3.
    - Top-level dict shape validated: must have a 'todos' key whose
      value is a list. Extra top-level keys are preserved (forward
      compat). Per-todo extra keys are preserved on each todo dict.
    """
    if not os.path.exists(path):
        return []
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        err(f"store at {path} is malformed: {e}", EXIT_IO)
    except (PermissionError, OSError) as e:
        err(f"cannot read store at {path}: {e}", EXIT_IO)
    if not isinstance(data, dict) or "todos" not in data or not isinstance(data["todos"], list):
        err(f"store at {path} has wrong shape (expected dict with 'todos' list)", EXIT_IO)
    if data.get("version") not in (None, VERSION):
        err(f"store at {path} is version {data.get('version')}; this code only supports version {VERSION}", EXIT_IO)
    return data["todos"]


def save_store(path, todos):
    """Atomically write `todos` to `path` as a versioned JSON document.

    Implementation: create a temp file in the same directory with
    mode 0600, write the JSON, fsync, then os.replace() into place.
    `os.replace()` is atomic on APFS (macOS) and ext4 (Linux) per the
    POSIX rename guarantee. A reader either sees the old file or the
    new file, never a partial write.
    """
    dirpath = os.path.dirname(path) or "."
    # Check if the existing file's mode, to preserve it on subsequent
    # writes. If the file doesn't exist (first write), default to 0600
    # for security (matches spec's "must not be world-readable" intent).
    try:
        existing_mode = os.stat(path).st_mode & 0o777
    except FileNotFoundError:
        existing_mode = 0o600

    fd, tmp = tempfile.mkstemp(prefix=".tutorial_todo.", dir=dirpath)
    try:
        os.chmod(tmp, existing_mode)
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            json.dump({"version": VERSION, "todos": todos}, f, indent=2, sort_keys=True)
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp, path)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


# ── Subcommands ────────────────────────────────────────────────────────
def cmd_add(args, path):
    text = args.text.strip()
    if not text:
        err("text required", EXIT_USAGE)
    todos = load_store(path)
    todo = {
        "id": make_id(todos),
        "text": text,
        "done": False,
        "created_at": now_iso(),
        "completed_at": None,
    }
    todos.append(todo)
    save_store(path, todos)
    print(f"added todo {todo['id']}: {text}")
    return EXIT_OK


def cmd_list(args, path):
    todos = load_store(path)
    if args.done:
        todos = [t for t in todos if t["done"]]
    elif args.open:
        todos = [t for t in todos if not t["done"]]
    if not todos:
        print("(no todos)")
        return EXIT_OK
    for t in sorted(todos, key=lambda t: t["id"]):
        marker = "✓" if t["done"] else " "
        print(f"[{t['id']}] [{marker}] {t['text']}")
    return EXIT_OK


def cmd_done(args, path):
    todos = load_store(path)
    try:
        t = find_todo(todos, args.tid)
    except NoSuchId as e:
        err(str(e), EXIT_USAGE)
    if t["done"]:
        print(f"todo {args.tid} already done")
        return EXIT_OK  # idempotent
    t["done"] = True
    t["completed_at"] = now_iso()
    save_store(path, todos)
    print(f"marked todo {args.tid} done")
    return EXIT_OK


def cmd_delete(args, path):
    todos = load_store(path)
    try:
        t = find_todo(todos, args.tid)
    except NoSuchId as e:
        err(str(e), EXIT_USAGE)
    todos.remove(t)  # identity-based, not index
    save_store(path, todos)
    print(f"deleted todo {args.tid}")
    return EXIT_OK


# ── Parser + dispatch ───────────────────────────────────────────────────
def build_parser():
    """Build the argparse parser. Top-level --store + subcommands.

    We pre-validate argv for unknown subcommands (before argparse sees
    them) so we can print usage to stdout and the error to stderr
    with the exact format the spec requires. argparse's own --help
    and --version paths still work because they're caught by KNOWN
    detection (starts with '-').
    """
    p = argparse.ArgumentParser(
        prog="tutorial",
        description="A minimal command-line todo list with JSON persistence.",
        add_help=False,  # we handle help ourselves for consistent error formatting
    )
    p.add_argument("--store", default=DEFAULT_PATH,
                   help=f"path to the JSON store (default: {DEFAULT_PATH})")
    sub = p.add_subparsers(dest="command")

    sp_add = sub.add_parser("add", add_help=False)
    sp_add.add_argument("text")

    sp_list = sub.add_parser("list", add_help=False)
    grp = sp_list.add_mutually_exclusive_group()
    grp.add_argument("--done", action="store_true", help="only show completed")
    grp.add_argument("--open", action="store_true",
                    help="only show open (not done) todos")

    sp_done = sub.add_parser("done", add_help=False)
    sp_done.add_argument("tid", type=int)

    sp_delete = sub.add_parser("delete", add_help=False)
    sp_delete.add_argument("tid", type=int)

    sp_help = sub.add_parser("help", add_help=False)

    return p


def print_usage():
    """Print the usage block to stdout (per spec US-5)."""
    print("Usage: tutorial [GLOBAL] <command> [args]")
    print()
    print("Global:")
    print("  --store PATH      path to the JSON store")
    print("                   (default: $HOME/.tutorial_todo.json)")
    print()
    print("Commands:")
    print("  add <text>        Add a todo (id is assigned automatically)")
    print("  list              List todos (--done or --open to filter)")
    print("  done <id>         Mark a todo as done (idempotent)")
    print("  delete <id>       Remove a todo by id")
    print("  help              Print this help")


def main(argv=None):
    argv = argv if argv is not None else sys.argv[1:]

    # Handle no-arg, help, and --help/-h before argparse.
    if not argv or argv[0] in ("help", "--help", "-h"):
        print_usage()
        return EXIT_OK

    # Pre-validate the subcommand. This catches "tutorial frobnicate"
    # before argparse does, so we can print the unknown-command
    # message to stderr AND the usage to stdout (per spec).
    #
    # We walk past global flags (--store PATH) to find the subcommand.
    known = {"add", "list", "done", "delete", "help"}
    sub_arg = None
    i = 0
    while i < len(argv):
        a = argv[i]
        if a == "--store":
            i += 2  # skip --store and its value
            continue
        if a.startswith("-"):
            i += 1  # skip other global flags (none defined today)
            continue
        sub_arg = a
        break
    if sub_arg is not None and sub_arg not in known:
        print(f"unknown command: {sub_arg}", file=sys.stderr)
        print_usage()
        return EXIT_USAGE

    p = build_parser()
    args = p.parse_args(argv)
    path = args.store

    if args.command is None:
        # argparse saw a --flag but no subcommand. Print usage and exit 2.
        print_usage()
        return EXIT_USAGE

    if args.command == "help":
        print_usage()
        return EXIT_OK

    # Dispatch. Each handler returns the exit code.
    if args.command == "add":
        return cmd_add(args, path)
    if args.command == "list":
        return cmd_list(args, path)
    if args.command == "done":
        return cmd_done(args, path)
    if args.command == "delete":
        return cmd_delete(args, path)

    # Unreachable.
    return EXIT_USAGE


if __name__ == "__main__":
    sys.exit(main())
